#!/bin/bash

#SBATCH --partition=gpu2080
#SBATCH --nodelist=gollum153
#SBATCH --time=20:00:00
#SBATCH --nodes=1           #number of nodes
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --no-requeue            #do not requeue on failure
#SBATCH --mem 50000M         #request 10GB RAM
#SBATCH --output=output/run_alphafold_3NIR.out

#Load Modules
module load alphafold/alphafold2


#run_alphafold.py args
data_dir='/export/apps/CentOS7/alphafold/data'
output_dir="/home/azamh/decarboxylases/models/"
fasta_paths="/home/azamh/decarboxylases/fasta/3NIR.fasta"
model_names='model_1,model_2,model_3,model_4,model_5,model_1_ptm,model_2_ptm,model_3_ptm,model_4_ptm,model_5_ptm'
max_template_date='2021-07-28'
preset='full_dbs' #casp14, full_dbs, reduced_dbs
benchmark=false


export CUDA_VISIBLE_DEVICES=0
export TF_FORCE_UNIFIED_MEMORY='1'
export XLA_PYTHON_CLIENT_MEM_FRACTION='4.0'

# Database paths
#bfd and uniclust databases need common string such as 'uniclust30_2018_08' that is found in all files
bfd_database_path="$data_dir/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt"
mgnify_database_path="$data_dir/mgnify/mgy_clusters.fa"
template_mmcif_dir="$data_dir/pdb_mmcif/mmcif_files"
obsolete_pdbs_path="$data_dir/pdb_mmcif/obsolete.dat"
pdb70_database_path="$data_dir/pdb70/pdb70"
uniclust30_database_path="$data_dir/uniclust30/uniclust30_2018_08/uniclust30_2018_08"
uniref90_database_path="$data_dir/uniref90/uniref90.fasta"

# Msa/template binary paths
hhblits_binary_path=$(which hhblits)
hhsearch_binary_path=$(which hhsearch)
jackhmmer_binary_path=$(which jackhmmer)
kalign_binary_path=$(which kalign)

python run_alphafold.py \
  --fasta_paths=$fasta_paths \
  --output_dir=$output_dir \
  --model_names=$model_names \
  --data_dir=$data_dir \
  --jackhmmer_binary_path="$jackhmmer_binary_path" \
  --hhblits_binary_path=$hhblits_binary_path \
  --hhsearch_binary_path=$hhsearch_binary_path \
  --kalign_binary_path=$kalign_binary_path \
  --uniref90_database_path=$uniref90_database_path \
  --mgnify_database_path=$mgnify_database_path \
  --bfd_database_path=$bfd_database_path \
  --uniclust30_database_path=$uniclust30_database_path \
  --pdb70_database_path=$pdb70_database_path \
  --template_mmcif_dir=$template_mmcif_dir \
  --max_template_date=$max_template_date \
  --obsolete_pdbs_path=$obsolete_pdbs_path \
  > output/run_alphafold_3NIR.log

